---

- name: uWSGI Config dir
  file:
    state: directory
    dest: "{{uwsgi_config_dir}}"
    owner: "{{uwsgi_user}}"
    group: "{{uwsgi_group}}"
    mode: "0755"
  
- name: uWSGI Vassals dir
  file:
    state: directory
    dest: "{{item}}"
    owner: "{{uwsgi_user}}"
    group: "{{uwsgi_group}}"
    mode: "0755"
  when: uwsgi_vassals_enabled
  with_items:
    - "{{uwsgi_vassals_available_dir}}"
    - "{{uwsgi_vassals_enabled_dir}}"

- name: uWSGI Log dir
  file:
    state: directory
    dest: "{{uwsgi_log_dir}}"
    owner: "{{uwsgi_user}}"
    group: "{{uwsgi_group}}"
    mode: "0755"

- name: uWSGI configuration file
  template:
    src: "etc/uwsgi/uwsgi.ini.j2"
    dest: "{{uwsgi_config_dir}}/uwsgi.ini"
    owner: "{{uwsgi_user}}"
    group: "{{uwsgi_group}}"
    mode: "0640"

- name: SystemD Unit File
  template:
    src: etc/systemd/system/uwsgi.service.j2
    dest: "{{uwsgi_systemd_unit_file}}"
    owner: "root"
    group: "root"
    mode: "0644"
  register: uwsgi_systemd_unit_updated
  when: ansible_service_mgr == "systemd"

- name: SystemD Reload
  systemd:
    name: uwsgi.service
    daemon_reload: yes
    enabled: yes
  when: 
    - ansible_service_mgr == "systemd"
    - uwsgi_systemd_unit_updated is succeeded

# vi:ts=2:sw=2:et:ft=yaml
