---

- name: Update APT cache
  apt:
    cache_valid_time=3600
    update_cache=yes

- name: Install uWSGI Prerequisites
  apt:
    state=present
    name="{{item}}"
  with_items: uwsgi_prereqs

- name: Install uWSGI
  pip:
    name=uwsgi
    version="{{uwsgi_version}}"

# vi:ts=2:sw=2:et:ft=yaml
