---

- name: Install uWSGI Prerequisites
  package:
    state: present
    name: "{{uwsgi_prereqs}}"

- name: Install uWSGI
  pip:
    state: present
    name: uwsgi
    version: "{{uwsgi_version|default('')}}"
    executable: "{{uwsgi_pip_executable}}"

# vi:ts=2:sw=2:et:ft=yaml
