---

- name: Install uWSGI Prerequisites
  package:
    state: present
    name: "{{item}}"
  with_items: "{{uwsgi_prereqs}}"

- name: Install uWSGI
  pip:
    state: present
    name: uwsgi
    version: "{{uwsgi_version|default('')}}"

# vi:ts=2:sw=2:et:ft=yaml
