---

- include: install.yml
  tags: uwsgi_install

- include: user.yml
  when: uwsgi_create_user
  tags: uwsgi_user

- include: config.yml
  tags: uwsgi_config

- include: vassals.yml
  when: uwsgi_vassals
  tags: uwsgi_vassals

# vi:ts=2:sw=2:et:ft=yaml
